blog/urls.py
# -*- coding: utf-8 -*-

"""kuzmin_site URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf.urls import include, url
from django.urls import reverse_lazy
from django.contrib.auth.views import LogoutView
from blog.views import Privet, PostsListView, PostDetailView, Post_YearArchiveView, Post_MonthArchiveView,\
    Post_DayArchiveView,  RegistrationView, LoginView, post_Create, PostDelete, PostUpdate


app_name = 'blog'

urlpatterns = [
    url(r'^$', Privet.as_view(), name='home'), # содержит описание сайта  и показывает первые [:10]
    url(r'^blog/$', PostsListView.as_view(), name='list'),
    url(r'^post/(?P<pk>\d+)/$', PostDetailView.as_view(), name='simple_post'),
    url(r'^post/create/$', post_Create.as_view(), name='create_post'),
    url(r'^post/(?P<pk>\d+)/delete/$', PostDelete.as_view(), name='delete_post'),
    url(r'^post/(?P<pk>\d+)/update/$', PostUpdate.as_view(), name='update_post'),
    url(r'^archive/(?P<year>\d{4})/$',  Post_YearArchiveView.as_view(),    name="Post_year_archive"),
    url(r'^archive/(?P<year>\d{4})/(?P<month>\d+)/$',   Post_MonthArchiveView.as_view(month_format='%m'),   name="month_numeric"),
    url(r'^archive/(?P<year>\d{4})/(?P<month>\d+)/(?P<day>\d+)/$', Post_DayArchiveView.as_view(month_format='%m', day_format='%d'),     name="Post_day_numeric"),
    url(r'^registration/$', RegistrationView.as_view(), name='registration'),
    url(r'^login_now/$', LoginView.as_view(), name='login_view'),
    url(r'^logout_now/$', LogoutView.as_view(next_page=reverse_lazy('blog:home')), name='logout'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

kuzmin_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
]

blog/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.urls import reverse


class Post(models.Model):
    user_post = models.ForeignKey(User,  on_delete=models.CASCADE, verbose_name=('Автор статьи'))
    title = models.TextField('Заголовок', max_length=255, default='')
    datetime = models.DateTimeField('Дата публикации')
    content = models.TextField('Содержание', default='')
    pub_date = models.DateField(auto_now_add=True)
    moder = models.BooleanField("Модерация", default=False)


    def get_absolute_url(self):
        return f"/post/{self.pk}/"

    def __str__(self):
        return self.title


class Comment(models.Model):
    user_comment = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name=('коментируемая статья'))


    message = models.TextField(max_length=1500, default='')
    timestamp = models.DateTimeField(auto_now_add=True)
    moder = models.BooleanField("Модерация", default=False)

    class Meta:
        ordering = ("-timestamp",)

    def __str__(self):
        return f"{self.user_comment} - {self.message[:30]}"


class UserAccount(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=200, default=None, blank=True, null=True )
    last_name = models.CharField(max_length=200, default=None, blank=True, null=True)
    email = models.EmailField(default=None, blank=True, null=True)
    faivorite_post = models.ManyToManyField(Post)

    class Meta:
        permissions = (('can_delete', 'can_create'),)

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('account_view', kwargs={'user':self.user.username})

blog/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.contrib.auth import get_user_model
from blog.models import Comment

User = get_user_model()



class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['message'].label = 'Место для Ваших комментариев'

    class Meta:
        model = Comment
        fields = ('message', )

class LoginForm(forms.Form):

    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        if not  User.objects.filter(username=username).exists():
            raise forms.ValidationError('Пользователя с этим именем не существует!!!')
        user = User.objects.get(username=username)
        if not user.check_password(password):
            raise forms.ValidationError('Пароль неверный!!!')

class RegistrationForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)
    password_check = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password',
            'password_check',

        ]
    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['username'].label = 'Авторский псевдоним'
        self.fields['password_check'].label = 'Повторите Ваш пароль'
        self.fields['email'].help_text = 'Обязательное поле'

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        password_check = self.cleaned_data['password_check']

        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('Пользователь с этим именем уже существует!!!')
        if password != password_check:
            raise forms.ValidationError('Пароль не совпадает!!!')

blog/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.http import JsonResponse, HttpResponseRedirect
from django.views.generic import DetailView, ListView, TemplateView, View
from django.views.generic.dates import YearArchiveView, MonthArchiveView, DayArchiveView
from django.contrib.auth import get_user_model, authenticate, login
from blog.urls import *
from blog.models import Post, Comment, UserAccount
from blog.forms import CommentForm, RegistrationForm, LoginForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin


User = get_user_model()

class Privet(TemplateView):
    model = Post
    template_name = "blog/home.html"
    allow_future = False

    def get_context_data(self, **kwargs):
        context = super(Privet, self).get_context_data(**kwargs)
        queryset = Post.objects.order_by('-datetime')[:10]
        context['list_home'] = [x for x in queryset]
        return context


class PostsListView(ListView):
    model = Post
    queryset = Post.objects.order_by('-datetime')
    template_name = "blog/post_list.html"


class PostDetailView(DetailView):
    model = Post
    template_name = "blog/post_detail.html"

    def get_context_data(self,  **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        comment_list = (
                            Comment.objects.filter(post=self.object).order_by('-timestamp')
                        )
        context['comment_tree'] = comment_list
        context['comment_form'] = CommentForm()
        context['avtor'] = Comment.user_comment
        context['comment_all'] = [x for x in comment_list]
        context['new_comment'] = None
        context['object'] = self.get_object()
        return context

    def post(self, request, *args, **kwargs):
        post = self.get_object()
        form = CommentForm(request.POST or None, instance=post)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.message = form.cleaned_data['message']
            new_comment.user_comment = request.user
            new_comment.save()
            Comment.objects.create(user_comment=new_comment.user_comment,
                                   message=new_comment.message,
                                   post=post
                                   )
            return HttpResponseRedirect(request.path_info)
        else:
            form = CommentForm()
        context = {
            'form': form
        }
        return render(self.request, self.template_name, context)


class Post_YearArchiveView(YearArchiveView):
    model = Post
    queryset = Post.objects.all()
    date_field = "datetime"     # Сортировать по дате публикации
    make_object_list = True     # передавать в контексте список статей
    allow_future = False    # Не показывать статьи с датой публикации в будующем

    template_name = "blog/archive.html"


class Post_MonthArchiveView(MonthArchiveView):
    model = Post
    queryset = Post.objects.all()
    date_field = "datetime"
    make_object_list = True
    allow_future = False
    template_name = "blog/month_archive.html"


class Post_DayArchiveView(DayArchiveView):
    model = Post
    queryset = Post.objects.all()
    date_field = "datetime"
    make_object_list = True
    allow_future = False
    template_name = "blog/day_archive.html"



class RegistrationView(View):
    template_name = 'blog/registration.html'

    def get(self, request, *args, **kwargs):

        form = RegistrationForm(request.POST or None)
        context = {
           "form": form
        }
        return render(self.request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = RegistrationForm(request.POST or None)
        if form.is_valid():
            new_user = form.save(commit=False)
            username = form.cleaned_data['username']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            new_user.set_password(password)
            password_check = form.cleaned_data['password_check']
            new_user.save()
            UserAccount.objects.create(user=User.objects.get(username=new_user.username),
                                       first_name=new_user.first_name,
                                       last_name=new_user.last_name,
                                       email=new_user.email)
            user = authenticate(username=username, password=password)
            login(self.request, user)
            return HttpResponseRedirect('/')
        context = {
            'form': form
        }
        return render(self.request, self.template_name, context)

class LoginView(View):
    template_name = 'blog/login.html'

    def get(self, request, *args, **kwargs):
        form = LoginForm(request.POST or None)
        context = {
            "form": form
        }
        return render(self.request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = LoginForm(request.POST or None)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user:
                login(self.request, user)
            return HttpResponseRedirect('/')
        context = {
            'form': form
        }
        return render(self.request, self.template_name, context)



class post_Create(PermissionRequiredMixin, CreateView):
    permission_required = 'can_create'
    model = Post
    fields = '__all__'


class PostUpdate(UpdateView):
    model = Post
    fields = ['user_post','datetime','moder']

class PostDelete(DeleteView):
    permission_required = 'can_delete'
    model = Post
    success_url = reverse_lazy('home')

blog/templates/blog/archive.html
{% extends 'blog/base.html' %}

    {% block opisanie %}

        <h1> Все статьи за  {{ year|date:"Y" }}</h1>

    {% endblock opisanie %}

{% block content %}
<ul>
    {% for date in date_list  %}
        <a href="{{ date|date:'m' }}"> <b>{{ date|date:"F" }}</b></a>
        {% for obj in object_list %}
            {% if obj.datetime|date:"F" ==  date|date:"F" %}
                <p>
                    <a href="{{ obj.get_absolute_url }}"><li>{{obj.title}}</a> - {{ obj.datetime|date:"F j, Y" }} автор {{ obj.user_post}}
                </p>
            {% endif %}
        {% endfor %}
    {% endfor %}
 </ul>
<p>
    {% if previous_year %}
        Предыдущий год : <a href="{% url 'blog:Post_year_archive' previous_year|date:'Y' %}"> <b>{{ previous_year|date:"Y" }}</b></a>
    {% endif %}
    {% if next_year %}
        Следующий год : <a href="{% url 'blog:Post_year_archive' next_year|date:'Y' %}"> <b>{{ next_year|date:"Y" }}</b></a>
    {% endif %}
</p>
{% endblock content %}

blog/templates/blog/base.html
{% load staticfiles %}
<html>
<head>
    {% load bootstrap4 %}
    {% bootstrap_javascript jquery='full' %}
    {% bootstrap_css %}
    <meta charset="utf-8">

    <title>{% block title %}Kuzmin Blog{% endblock %}</title>

</head>
<body>
    <!-- header -->
  <header class="blog-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">

      <div class="col-2 text-left">
          <ul>
              <a class="blog-header-logo text-dark" href="{% url 'blog:Post_year_archive'  2019  %}">Архив {{  obj.datetime|date:'Y' }}</a>
          </ul>
      </div>
        <div class="col-3 text-left">
          <ul>
              <a class="blog-header-logo text-dark" href="{% url 'blog:list'  %}">Список статей</a>
          </ul>
      </div>
        <div class="col-3 text-left">
          <ul>
              <a class="blog-header-logo text-dark" href="{% url 'blog:home' %}"><h4>Kuzmin Blog Главная</h4></a>
          </ul>
      </div>
      <div class="col-4 d-flex justify-content-end align-items-center">
            {% if not user.is_authenticated %}
            <ul>
                        <a class="btn btn-sm btn-outline-secondary" href="{% url 'blog:login_view' %}?next={{request.path}}">Войти</a>


            </ul>

            <ul>
                        <a class="btn btn-sm btn-outline-secondary" href="{% url 'blog:registration' %}">Зарегистрироваться</a>
            </ul>
            {% endif %}

        {% if user.is_authenticated %}
            <ol>
                        <a class="btn btn-sm btn-outline-secondary" href="{% url 'blog:logout' %}?next={{request.path}}">Разлогиниться</a>

            </ol>
        {% endif %}

         {% if  user.is_staff %}
             <ul>
                        <a class="btn btn-sm btn-outline-secondary" href="{% url 'blog:create_post' %}">Запостить новую статью</a>

            </ul>
         {% endif %}




      </div>
    </div>
  </header>
    <!-- Navigator -->

    <div class="container">
    <p class="text-centr"><img src='{% static "images/sitelogo.jpeg" %}' alt="Logo" width="100%" height="35%"></p>
    </div>

    <div class="container">
        {% block opisanie %}

        {% endblock opisanie %}
    </div> <!-- container -->



    <div class="container">
        {% block content %}Empty page{% endblock content %}
    </div> <!-- container -->


<footer class="blog-footer">
  <p class="col-12 text-center">Сделанно в процессе обучения студента<a style="text-decoration:none" href="#"> Кузьмин Михаил Сергеевич</a>.
      <a style="text-decoration:none" class="text-centr" href="#" >(вернуться вверх)</a> Copyright &copy; </p>
</footer>


</body>
</html>

blog/templates/blog/day_archive.html
{% extends 'blog/base.html' %}

    {% block opisanie %}
        <h1> Все статьи за  {{ day }}</h1>
    {% endblock opisanie %}

{% block content %}
<ul>
    {% for obj in object_list %}
        <p>
            <li><a href="{{ obj.get_absolute_url }}">{{obj.title}}</a> -  автор {{ obj.user_post}}
        </p>
    {% endfor %}
</ul>
<p>
    {% if previous_day %}
        Предыдущий день : <a href="{% url 'blog:Post_day_numeric' previous_day|date:'Y' previous_day|date:'m'  previous_day|date:'d' %}"> <b>{{ previous_day|date:"j F Y" }}</b></a>
    {% endif %}

    {% if previous_day and next_day %} --- {% endif %}

    {% if next_day %}
        Следующий день : <a href="{% url 'blog:Post_day_numeric' next_day|date:'Y' next_day|date:'m'  next_day|date:'d' %}"> <b>{{ next_day|date:"j F Y" }}</b></a>
    {% endif %}
</p>

{% endblock content %}

blog/templates/blog/home.html
{% extends 'blog/base.html' %}

{% block opisanie %}
<div><h2>Это блог о том как я учился в DL ACADEMY и чему научился...</h2></div>
<br>
    {% if user.is_authenticated %}
        <h2>Мы рады видеть Вас, <b>{{ user.username }}</b> на нашей площадке.</h2>
    {% else %}
        <p>Добро пожаловать. Пожалуйста авторизуйтесь или зарегистрируйтесь.</p>
    {% endif %}
<hr>
{% endblock opisanie %}

{% block content %}
    <ul class="nav">
        <p><h3>Список самых свежих постов</h3></p>
    </ul>
    {% for list in list_home %}
         <h3><a href="{{ list.get_absolute_url }}"><li>{{list.title}}</a> -- {{ list.datetime }}</li></h3>
    {% endfor %}
{% endblock content %}

blog/templates/blog/month_archive.html
{% extends 'blog/base.html' %}

    {% block opisanie %}
        <h1> Все статьи за  {{ month|date:"F" }}</h1>
    {% endblock opisanie %}

{% block content %}
<ul>
    {% for date in date_list  %}
        <a href="{{ date|date:'j' }}"> <b>{{ date|date:"F j" }}</b></a>

        {% for obj in object_list %}


                {% if obj.datetime|date:"F j" ==  date|date:"F j" %}

                    <p>
                        <li><a href="{{ obj.get_absolute_url }}">{{obj.title}}</a> -  автор {{ obj.user_post}}
                    </p>

                {% endif %}
        {% endfor %}
    {% endfor %}
</ul>

<p>
    {% if previous_month %}
        Предыдущий месяц : <a href="{% url 'blog:month_numeric' previous_month|date:'Y'  previous_month|date:'m' %}"> <b>{{ previous_month|date:"F Y" }}</b></a>
    {% endif %}
    {% if next_month %}
        Следующий месяц : <a href="{% url 'blog:month_numeric' next_month|date:'Y'  next_month|date:'m' %}"> <b>{{ next_month|date:"F Y" }}</b></a>
    {% endif %}
</p>

{% endblock content %}

blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}

{% block content %}

<h1>Удаление Статьи</h1>

<p>Вы удаляете статью: {{ author }}. Подтвердите свои намерения!</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="ДА, это была лишняя статья." />
</form>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    {{ object.title }}
{% endblock title %}

{% block opisanie %}
    <h1 class="text-centr">{{ object.title }}</h1>
    <p><b>{{ post.datetime }}</b></p>
{% endblock opisanie %}

{% block content %}

    <p>{{ post.content|escape|linebreaks }}</p>

    {% if not user.is_authenticated %}
        <h5 class="border-bottom border-gray pb-2 mb-0">Хотите оставить комментарий? Тогда войдите или зарегистрируйтесь</h5>

    {% endif %}

    {% if comment_tree %}
        <div class="my-3 p-3 bg-white rounded shadow-sm">
            <h6 class="border-bottom border-gray pb-2 mb-0">Коментарии</h6>
            {% for comment in comment_tree.all reversed %}
            <div class="media text-muted pt-3">
                <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                    <strong class="d-block text-gray-dark">
                        {{ comment.timestamp }}  комментарий от - <b>{{ comment.user_comment }}</b></strong>
                        {{ comment.message }}
                </p>
            </div>
            {% empty %}
                <p> Будь первым и поделись своим мнением. </p>
            {% endfor %}
        </div>
    {% endif %}

        <!-- Comment Form -->
    {% if user.is_authenticated %}
        {% if new_comment %}
            <p>Спасибо за Ваш комментарий</p>
        {% else %}
        <form action="" method="POST" >
                {% csrf_token %}
                {{ comment_form|crispy }}
            <input  type="submit" value="Отправить" id="add_commit">
        </form>
        {% endif %}
    {% endif %}


{% endblock content %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Опубликовать" />

</form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block opisanie %}
            <ul class="nav">
                <li>Список постов</li>
            </ul>
{% endblock opisanie %}

{% block content %}
    {% for post in object_list %}
        <p>{{ post.datetime }}</p>
        <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
        <p>{{ post.content|escape|linebreaks|truncatewords:30 }}</p>
    {% empty %}
    <p>Пока никто ничего не написал</p>
    {% endfor %}

{% endblock %}

blog/templates/blog/registration.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-offset-sm-4">
                <div class="container">
                    <h3 class="text-center">
                        Регистрация нового пользователя
                    </h3>
                </div>
                <hr>
                <form action="" method="POST">
                    {{ form.error }}
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="submit" value="Зарегистрироваться">
                </form>
            </div>

        </div>


    </div>


{% endblock content %}